---
- hosts: lb
 
  roles:
    - role: nginx
      when: enable_nginx_lb | bool and load_balancer_is_required | bool

    - role: apache
      when: enable_apache_lb | bool and load_balancer_is_required | bool
