[nfs]
172.31.57.222 ansible_ssh_user=ec2-user

[webservers]
172.31.189.178 ansible_ssh_user=ec2-user
172.31.222.77 ansible_ssh_user=ec2-user

[db]
172.31.176.122 ansible_ssh_user=ubuntu

[lb]
18.194.126.158 ansible_ssh_user=ubuntu
