[uat-webservers]
13.53.163.8 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/home/ubuntu/key.pem
13.51.47.86 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/home/ubuntu/key.pem

[lb]
51.20.86.98 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/key.pem

[db-servers]
51.20.141.152 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/key.pem

