---

artifactory_license: oss

artifactory_file_license: "artifactory-{{ artifactory_license }}"
artifactory_file: "jfrog-{{ artifactory_file_license }}"
artifactory_file_version: "{{ artifactory_file }}-{{ artifactory_version }}"
artifactory_file_version_platform: "{{ artifactory_file_version }}-linux.tar.gz"
artifactory_url: "https://api.bintray.com/content/jfrog/artifactory/org/artifactory/{{ artifactory_license }}/{{ artifactory_file }}/{{ artifactory_version }}/{{ artifactory_file_version_platform }};bt_package={{ artifactory_file }}"

artifactory_home_full: "{{ jfrog_home }}/{{ artifactory_file_license }}-{{ artifactory_version }}" # Distr archive name

artifactory_os_user_name: "artifactory"
artifactory_os_service_name: "artifactory"
