pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    sh '''
                    echo "Building Stage"
                    '''
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh '''
                    echo "Testing Stage"
                    '''
                }
            }
        }
         stage('Package') {
            steps {
                script {
                    sh '''
                    echo "packagage Stage"
                    '''
                }
            }
        }
         stage('Deploy') {
            steps {
                script {
                    sh '''
                    echo "Deploy Stage"
                    '''
                }
            }
        }
         stage('Cleanup') {
            steps {
                script {
                    sh '''
                    echo "Cleanup Stage"
                    '''
                }
            }
        }
    }
}
