mysql_root_password:
mysql_databases:
  - name: tooling
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: admin
    host: "172.31.16.0/20"
    password: admin
    priv: "tooling.*:ALL"
