mysql_root_password:
mysql_databases:
  - name: tooling
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: admin
    host: "127.0.0.1"
    password: admin
    priv: "tooling.*:ALL"
