mysql_root_password:
mysql_databases:
  - name: homestead
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: homestead
    host: "%"
    password: sePret^i
    priv: "*.*:ALL"
