- name: Remove Apache
  become: true
  ansible.builtin.package:
    name: httpd
    state: absent

- name: Remove Apache configuration directory
  become: true
  ansible.builtin.file:
    path: /etc/httpd
    state: absent

- name: Remove Apache data directory
  become: true
  ansible.builtin.file:
    path: /var/www/html
    state: absent

- name: Remove Apache log directory
  become: true
  ansible.builtin.file:
    path: /var/log/httpd
    state: absent

