---
- name: Install Apache
  remote_user: ubuntu
  become: true
  become_user: root
  ansible.builtin.apt:
    name: "apache2"
    state: present

- name: Install Git
  remote_user: ubuntu
  become: true
  become_user: root
  ansible.builtin.apt:
    name: "git"
    state: present

- name: Install PHP and extensions
  remote_user: ubuntu
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - php
      - libapache2-mod-php
      - php-opcache
      - php-gd
      - php-curl
      - php-mysql
    state: present

- name: Restart Apache to load PHP module
  remote_user: ubuntu
  become: true
  become_user: root
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Remove existing html directory if it exists
  remote_user: ubuntu
  become: true
  become_user: root
  ansible.builtin.file:
    path: /var/www/html
    state: absent

- name: Clone a repo
  remote_user: ubuntu
  become: true
  become_user: root
  ansible.builtin.git:
    repo: https://github.com/citadelict/tooling.git
    dest: /var/www/html
    force: yes
    update: yes

- name: Copy HTML content to one level up
  remote_user: ubuntu
  become: true
  become_user: root
  command: cp -r /var/www/html/html/ /var/www/

- name: Start apache2 service, if not started
  remote_user: ubuntu
  become: true
  become_user: root
  ansible.builtin.service:
    name: apache2
    state: started

- name: Recursively remove /var/www/html/html directory
  remote_user: ubuntu
  become: true
  become_user: root
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent
