---
- name: Install and configure LAMP stack with PHP 7.4 on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - apache2
          - git
          - software-properties-common
        state: present

    - name: Add PHP PPA
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt cache after adding PHP PPA
      ansible.builtin.apt:
        update_cache: yes

    - name: Install PHP and extensions
      ansible.builtin.apt:
        name:
          - php7.4
          - php7.4-opcache
          - php7.4-gd
          - php7.4-curl
          - php7.4-mysql
        state: present
      notify:
        - restart apache2

    - name: Set SELinux boolean for httpd_execmem
      ansible.builtin.seboolean:
        name: httpd_execmem
        state: true
        persistent: yes
      when: ansible_selinux.status == "enabled"

    - name: Clone a repo
      ansible.builtin.git:
        repo: https://github.com/citadelict/tooling.git
        dest: /var/www/html
        force: yes

    - name: Copy HTML content to one level up
      ansible.builtin.command:
        cmd: cp -r /var/www/html/html/ /var/www/
      
    - name: Recursively remove /var/www/html/html directory
      ansible.builtin.file:
        path: /var/www/html/html
        state: absent

    - name: Start and enable apache2 service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

  handlers:
    - name: restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
