---
- name: Update webservers, NFS, create directory, change timezone
  hosts: webservers, nfs
  become: yes
  tasks:
    - name: Ensure Wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: Create a directory
      file:
        path: /tmp/testdir
        state: directory
        mode: '0755'

    - name: Create a file inside the directory
      copy:
        dest: /tmp/testdir/testfile
        content: "This is a file created by Ansible."
        mode: '0644'

    - name: Change timezone to UTC
      timezone:
        name: Etc/UTC

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

- name: Update Load balancer and DB, create directory, change timezone
  hosts: lb, db
  become: yes
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: Ensure Wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

    - name: Create a directory
      file:
        path: /tmp/testdir
        state: directory
        mode: '0755'

    - name: Create a file inside the directory
      copy:
        dest: /tmp/testdir/testfile
        content: "This is a file created by Ansible."
        mode: '0644'

    - name: Change timezone to UTC
      timezone:
        name: Etc/UTC

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Add host key to known hosts
      shell: ssh-keyscan -H 172.31.134.226 >> ~/.ssh/known_hosts
      args:
        warn: false
