---

- name: "Ensure hardware pre-requisites for Artifactory {{ artifactory_file_version }} with default embedded Derby database"
  tags: hardware_check
  assert:
    that:
      - ansible_processor_vcpus >= 1 # Virtual CPU cores.
      - ansible_memfree_mb >= 1024 # Free RAM mb for comfort Artifactory experience
      - ((ansible_mounts|first).size_available|float / 1000000000) >= 1 # Free disk Gb for Artifactory installation and metadata.

- name: Ensure unzip utility
  tags: unzip
  package: 
    name: unzip
    state: present


- name: Stop linux service
  tags: service
  service:
    name: "{{ artifactory_os_service_name }}"
    state: stopped
  ignore_errors: yes


- name: Get rid of old Artifactory configuration
  tags: config
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ artifactory_home }}/var/etc/access/bootstrap.creds"
    - "{{ artifactory_home }}/var/etc/system.yaml"
    - "{{ artifactory_home }}/var/etc/artifactory/artifactory.system.properties"
    - "{{ artifactory_home }}/var/etc/artifactory/logback.xml"
    - "{{ artifactory_home }}/var/etc/artifactory/binarystore.xml"
    - "{{ artifactory_home }}/var/etc/artifactory/artifactory.config.import.xml"
