---
# tasks file for installing Artifactory distribution

- name: Create user to run Artifactory
  ansible.builtin.user:
    name: "{{ artifactory_os_user_name }}"
    comment: "User to run Artifactory"
    shell: /bin/bash
    system: yes

- name: Create JFROG_HOME folder
  ansible.builtin.file:
    path: "{{ jfrog_home }}"
    state: directory
    owner: "{{ artifactory_os_user_name }}"
    group: "{{ artifactory_group }}"
    mode: "0755"

- name: Download and unarchive Artifactory distr
  block:
    - name: Download Artifactory
      ansible.builtin.get_url:
        url: "{{ artifactory_url }}"
        dest: "/tmp/{{ artifactory_file_version_platform }}"
        mode: '0644'
      register: download_artifactory
      retries: 3
      delay: 10
      until: download_artifactory is succeeded

    - name: Check if the archive file is not empty
      ansible.builtin.stat:
        path: "/tmp/{{ artifactory_file_version_platform }}"
      register: artifactory_archive

    - name: Fail if the archive is empty
      ansible.builtin.fail:
        msg: "The downloaded Artifactory archive is empty."
      when: artifactory_archive.stat.size == 0

    - name: Extract Artifactory
      ansible.builtin.unarchive:
        src: "/tmp/{{ artifactory_file_version_platform }}"
        dest: "{{ jfrog_home }}"
        remote_src: yes
  when: artifactory_archive.stat.size != 0
