---

- name: Set up linux service file
  tags: service
  template:
    src: artifactory
    dest: "/etc/init.d/{{ artifactory_os_service_name }}"
    owner: "{{ artifactory_os_user_name }}"
    group: "{{ artifactory_os_user_name }}"
    mode: u=rwx,g=rx,o=rx

- name: Set up Artifactory access to linux log directory
  tags: service
  file:
    path: /var/log/artifactory.log
    state: touch
    owner: "{{ artifactory_os_user_name }}"
    group: "{{ artifactory_os_user_name }}"
    mode: u=rw,g=rw,o=r

- name: Register Artifactory linux service
  tags: service
  command: "update-rc.d {{ artifactory_os_service_name }} defaults"
  notify: Restart Artifactory linux service
