---

- name: Sound-check
  include: 01-pre-requisites.yml

- name: Install Artifactory distr
  include: 02-install-distr.yml

- name: Configure Artifactory
  include: 03-configure-distr.yml

- name: Install databse driver
  include: 04-install-db-driver.yml

- name: Set up Artifactory as linux service
  include: 05-install-service.yml
