---
# tasks file for artifactory

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Download JFrog GPG key
  ansible.builtin.shell:
    cmd: wget -qO - https://releases.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -

- name: Add JFrog Artifactory repository
  ansible.builtin.shell:
    cmd: echo "deb https://jfrog.bintray.com/artifactory-debs focal main" | sudo tee /etc/apt/sources.list.d/jfrog.list

- name: Update apt cache again
  ansible.builtin.apt:
    update_cache: yes

- name: Install JFrog Artifactory OSS
  ansible.builtin.apt:
    name: jfrog-artifactory-oss
    state: present

- name: Start Artifactory service
  ansible.builtin.systemd:
    name: artifactory
    state: started
    enabled: yes
