---
# tasks file for artifactory

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install prerequisite packages
  ansible.builtin.apt:
    name: wget
    state: present

- name: Download JFrog GPG key and add it to apt
  ansible.builtin.shell: |
    wget -qO - https://releases.jfrog.io/artifactory/api/gpg/key/public | apt-key add -
  register: gpg_key
  changed_when: "'OK' in gpg_key.stdout"

- name: Add JFrog Artifactory repository
  ansible.builtin.shell: |
    echo "deb [arch=amd64] https://releases.jfrog.io/artifactory/artifactory-debs bionic main" > /etc/apt/sources.list.d/jfrog.list

- name: Update apt cache again
  ansible.builtin.apt:
    update_cache: yes

- name: Install JFrog Artifactory OSS
  ansible.builtin.apt:
    name: jfrog-artifactory-oss
    state: present

- name: Start Artifactory service
  ansible.builtin.systemd:
    name: artifactory
    state: started
    enabled: yes

- name: Verify Artifactory service status
  ansible.builtin.systemd:
    name: artifactory
    state: started
    enabled: yes
    register: artifactory_status

- name: Ensure Artifactory is running
  ansible.builtin.debug:
    msg: "Artifactory is installed and running"
  when: artifactory_status.status.ActiveState == "active"
