---
# tasks file for artifactory

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install prerequisite packages
  ansible.builtin.apt:
    name: gnupg2
    state: present

- name: Add JFrog GPG key
  ansible.builtin.command: wget -qO - https://api.bintray.com/orgs/jfrog/keys/gpg/public.key | apt-key add -
  register: gpg_key
  changed_when: "'OK' in gpg_key.stdout"

- name: Add JFrog Artifactory repository
  ansible.builtin.command: echo "deb https://jfrog.bintray.com/artifactory-debs bionic main" | tee /etc/apt/sources.list.d/jfrog.list

- name: Update apt cache again
  ansible.builtin.apt:
    update_cache: yes

- name: Install JFrog Artifactory OSS
  ansible.builtin.apt:
    name: jfrog-artifactory-oss
    state: present

- name: Start Artifactory service
  ansible.builtin.systemd:
    name: artifactory
    state: started
    enabled: yes

- name: Verify Artifactory service status
  ansible.builtin.systemd:
    name: artifactory
    state: started
    enabled: yes
    register: artifactory_status

- name: Ensure Artifactory is running
  ansible.builtin.debug:
    msg: "Artifactory is installed and running"
  when: artifactory_status.status.ActiveState == "active"
