# tasks file for artifactory on Ubuntu

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Ensure python3-update-manager is installed from focal-updates
  ansible.builtin.command:
    cmd: apt-get install -y python3-update-manager
  become: yes

- name: Add JFrog GPG key
  ansible.builtin.shell: |
    wget -qO - https://releases.jfrog.io/artifactory/api/gpg/key/public | apt-key add -
  become: yes

- name: Add JFrog repository
  ansible.builtin.shell: |
    echo "deb https://jfrog.bintray.com/artifactory-debs focal main" | tee /etc/apt/sources.list.d/jfrog.list
  become: yes

- name: Update apt cache after adding JFrog repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install JFrog Artifactory OSS
  ansible.builtin.apt:
    name: jfrog-artifactory-oss
    state: present

- name: Enable and start artifactory service
  ansible.builtin.systemd:
    name: artifactory
    state: started
    enabled: yes

- name: Check status of artifactory service
  ansible.builtin.command: systemctl status artifactory.service
  become: yes
  register: result

- name: Display artifactory service status
  debug:
    var: result.stdout
