# tasks file for artifactory on Ubuntu

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install python3-update-manager
  ansible.builtin.apt:
    name: python3-update-manager
    state: latest

- name: Add JFrog GPG key
  ansible.builtin.apt_key:
    url: https://releases.jfrog.io/artifactory/api/gpg/key/public
    state: present

- name: Add JFrog repository
  ansible.builtin.shell: echo "deb https://jfrog.bintray.com/artifactory-debs focal main" | sudo tee /etc/apt/sources.list.d/jfrog.list
  args:
    executable: /bin/bash

- name: Update apt cache after adding JFrog repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install JFrog Artifactory OSS
  ansible.builtin.apt:
    name: jfrog-artifactory-oss
    state: present

- name: Enable and start artifactory service
  ansible.builtin.systemd:
    name: artifactory
    state: started
    enabled: yes

- name: Check status of artifactory service
  ansible.builtin.shell: systemctl status artifactory.service
  args:
    executable: /bin/bash
  register: result

- name: Display artifactory service status
  debug:
    var: result.stdout
