# tasks file for artifactory on Ubuntu

- name: Update apt cache and install dependencies
  ansible.builtin.apt:
    name: 
      - openjdk-17-jdk
      - wget
      - unzip
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: yes

- name: Configuring java path
  ansible.builtin.template:
    src: templates/bash-profile.j2
    dest: /home/ubuntu/.bash_profile
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Reload the .bash_profile
  ansible.builtin.shell: source /home/ubuntu/.bash_profile
  args:
    executable: /bin/bash

- name: Download JFrog Artifactory package
  ansible.builtin.get_url:
    url: https://releases.jfrog.io/artifactory/artifactory-debs/pool/jfrog-artifactory-oss-7.17.13.deb
    dest: /tmp/jfrog-artifactory-oss-7.17.13.deb

- name: Install JFrog Artifactory package
  ansible.builtin.command: dpkg -i /tmp/jfrog-artifactory-oss-7.17.13.deb
  become: yes

- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: -f
    state: present

- name: Start and enable artifactory
  ansible.builtin.systemd:
    name: artifactory
    state: started
    enabled: yes
