---
# tasks file for installing Artifactory

# - name: Change hostname to Artifactory
#   ansible.builtin.hostname:
#     name: Artifactory

# - name: Update /etc/hosts with the new hostname
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     regexp: '^127\.0\.1\.1\s+.*'
#     line: '127.0.1.1 Artifactory'
#     state: present

- name: Update Ubuntu OS
  ansible.builtin.apt:
    update_cache: yes

- name: Add JFrog Artifactory APT repository
  ansible.builtin.copy:
    content: "deb https://releases.jfrog.io/artifactory/artifactory-debs bionic main"
    dest: /etc/apt/sources.list.d/artifactory.list

- name: Download apt key
  ansible.builtin.get_url:
    url: "https://releases.jfrog.io/artifactory/api/gpg/key/public"
    dest: "/tmp/artifactory.gpg"

- name: Add a key from a file
  ansible.builtin.apt_key:
    file: "/tmp/artifactory.gpg"
    state: present

- name: Update the package list
  ansible.builtin.apt:
    update_cache: yes

- name: Install Artifactory
  ansible.builtin.apt:
    name: jfrog-artifactory-oss
    state: present

- name: Start Artifactory service
  ansible.builtin.systemd:
    name: artifactory.service
    state: started

- name: Enable Artifactory service
  ansible.builtin.systemd:
    name: artifactory.service
    enabled: yes

- name: Check Artifactory service status
  ansible.builtin.systemd:
    name: artifactory.service
    register: artifactory_status

- name: Ensure Artifactory is running
  ansible.builtin.debug:
    msg: "Artifactory is installed and running"
  when: artifactory_status.status.ActiveState == "active"
